apps/urls.py
from django.urls import path
from apps.views.users import *
from apps.rest_api.user import *
from apps.views.items import * 
from apps.views.carts import *
from apps.views.orders import *


urlpatterns = [
    # Normal django urls

    # User urls
    path('signup/',signup,name='signup'),
    path('verify/<str:email>/',verify,name='verify'),
    path('logout/',logout_user,name='logout'),
    path('signin/',signin,name='signin'),
    path('user_details/',user_details,name='user_details'),
    # Add the following URL patterns
    path('forgot_password/', forgot_password, name='forgot_password'),
    path('reset_password/<str:email_b64>/', reset_password, name='reset_password'),
    # item Urls
    path('', item_list, name='item_list'),
    path('item/<int:item_id>/', item_detail, name='item_detail'),
    path('item/add/', add_item, name='add_item'),
    path('item/edit/<int:item_id>/', edit_item, name='edit_item'),
    path('item/delete/<int:item_id>/', delete_item, name='delete_item'),
    path('about/', about, name='about'),
    path('item_list/<int:category_id>/', filter_items_by_category, name='filter_items_by_category'),
    path('contact/',contact,name='contact'),
    path('subscribe',subscribe,name='subscribe'),
    ###### Wishlist urls ############

    path('add_to_wishlist/<int:item_id>/', add_to_wishlist, name='add_to_wishlist'),
    path('view_wishlist/', view_wishlist, name='view_wishlist'),
    path('wishlist/remove/<int:wishlist_item_id>/', remove_from_wishlist, name='remove_from_wishlist'),
    # Cart urls 

    path('add_to_cart/<int:item_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', view_cart, name='cart'),
    path('update_quantity/<int:cart_item_id>/', update_quantity, name='update_quantity'),
    path('remove_from_cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),

    # Order urls 

    path('place_order/', place_order, name='place_order'),
    path('order_confirmation/', order_confirmation, name='order_confirmation'),
    path('orders/', order_list, name='order_list'),
    path('orders/<int:order_id>/update_tracking/', update_tracking, name='update_tracking'),

    # rest api endpoints 
    path('rest_signup/',SignUpView.as_view(), name='rest_signup'),
    path('rest_signin/',SigninView.as_view(),name='rest_signin'),
    path('rest_logout/',LogoutView.as_view(), name='rest_logout'),
    path('rest_verify/<str:email>/',VerifyOtpView.as_view(), name='VerifyRestEmail'),
]

clothing_project/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
# from apps.rest_api.

# from rest_framework_swagger.views import get_swagger_view

from django.urls import path, include
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Meal Mate",
        default_version='v1',
        description="This app is used to order food from the native restaurant",
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.urls')),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('swagger.json/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    # path('swagger/', get_swagger_view(title='My API')),
    
]

apps/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import UserManager
from rest_framework.authtoken.models import Token
from datetime import timedelta
from django.utils import timezone
from cloudinary.models import CloudinaryField
import secrets
from django.contrib.auth.models import AbstractUser, Group, Permission
# Create your models here.

#Common Fields for every table

class Common(models.Model):
    created_at = models.DateTimeField(auto_now_add=True,blank=False,null=False)
    updated_at = models.DateTimeField(auto_now=True,blank=False,null=False)

    class Meta:
        abstract = True


# User table 


class User(AbstractUser):
    phone_number = models.CharField(max_length=20, blank=True)
    is_verified = models.BooleanField(default=False)
    otp = models.CharField(max_length=20, blank=True, null=True)
    username = models.CharField(max_length=150, unique=True, null=True, blank=True)
    password = models.CharField(max_length=100, null=False, blank=True)
    email = models.EmailField(unique=True, blank=True)
    address = models.TextField(max_length=250, blank=True)
    jwt_token = models.CharField(max_length=250, unique=True, null=True, blank=True)
    token = models.CharField(max_length=250, unique=True, null=True, blank=True)
    is_logged_in = models.BooleanField(default=False)
    display_picture = CloudinaryField('Display Picture', null=True, blank=True)
    objects = UserManager()

    # Use 'phone_number' as the unique identifier for authentication
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username','phone_number']

    class Meta:
        db_table = 'User'

    def save_token(self, *args, **kwargs):
        if not self.token:
            # generate new token if none exists
            self.token = secrets.token_urlsafe(32)

        super().save(*args, **kwargs)

    def update_token(self):
        self.token = None
        self.token_created = None
        self.token_expires = None
        self.save()

########### Category Table ##############


class Category(models.Model):
    class Meta:
        db_table = 'Category'
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


################ Item Model ###################


class Size(models.Model):
    class Meta:
        db_table = 'Cloth sizes'
    sizes = models.CharField('Item size',max_length=5,blank=False,null=False)

    def __str__(self):
        return self.sizes

class Items(models.Model):
    class Meta:
        db_table = 'Item'
    
    item_name = models.CharField(max_length=50,blank=False,null=False)
    item_price = models.FloatField(blank=False,null=False)
    size = models.ManyToManyField(Size,blank=False)
    item_image = CloudinaryField("Item Image",blank=False,null=False)
    is_available = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    inventory = models.IntegerField(default=0)

    def __str__(self):
        return self.item_name
    
##################### Cart Model ####################


class Cart(models.Model):
    class Meta:
        db_table = 'Cart'
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField('Items', through='CartItem')

    def __str__(self):
        return f"Cart for {self.user.username}" 
    

class CartItem(models.Model):
    class Meta:
        db_table = 'Cart_Items'
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    item = models.ForeignKey('Items', on_delete=models.CASCADE)
    size = models.ForeignKey('Size', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)  # New field for quantity
    
    def __str__(self):
        return f"{self.cart} - {self.item.item_name} ({self.size.sizes}) - Quantity: {self.quantity}"
    @property
    def total_price(self):
        return self.item.item_price * self.quantity


############ order model ####################


class Order(models.Model):
    PAYMENT_CHOICES = (
        ("CASH ON DELIVERY", "COD"),
        ("UPI", "UPI"),
        ("CARD", "CARD"),
    )
    TRACKING = (
        ('SHIPPED','shipped'),
        ('ON THE WAY','on the way'),
        ('DELIVERED','delivered')
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    zip_code = models.CharField(max_length=10)
    place = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=20, choices=PAYMENT_CHOICES)
    tracking = models.CharField(max_length=20,choices=TRACKING,blank=True,null=True)
    def __str__(self):
        return f"Order #{self.pk} - {self.user.username}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey('apps.Items', on_delete=models.CASCADE)
    size = models.ForeignKey('apps.Size', on_delete=models.CASCADE)
    quantity = models.IntegerField(null=False, blank=False)
    total_price = models.IntegerField(null=False, blank=False)
    def __str__(self):
        return f"{self.order} - {self.item.item_name} ({self.size.sizes})"
    

############# Wishlist ################


class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Items, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username}'s Wishlist: {self.item.name}"
    


################# subscriber model ##############################


class Subscriber(models.Model):
    name = models.CharField(max_length=100,blank=False,null=False)
    email = models.EmailField(unique=True, blank=True)

apps/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from apps.models import *
#######################Sign UP form##################################

import phonenumbers

def validate_phone_number(phone_number):
    try:
        parsed_number = phonenumbers.parse(phone_number, None)
        if phonenumbers.is_valid_number(parsed_number):
            return True
        else:
            return False
    except phonenumbers.phonenumberutil.NumberParseException:
        return False
    

class SignUpForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'UserName'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input--style-2','placeholder': 'Password'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input--style-2','placeholder': 'Email'}))
    country_code = forms.ChoiceField(choices=[('+91', '+91 - India'),('+92', '+92 - Pakistan')], widget=forms.Select(attrs={'class': 'input--style-2'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2','placeholder': 'Phone Number'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2','placeholder': 'Address'}))

    class Meta:
        model = User
        fields = ('username', 'password', 'email', 'country_code', 'phone_number', 'address')

    def clean_phone_number(self):
        country_code = self.cleaned_data.get('country_code')
        phone_number = self.cleaned_data.get('phone_number')
        full_phone_number = ''

        if country_code and phone_number:
            full_phone_number = country_code + phone_number

        if not validate_phone_number(full_phone_number):
            raise forms.ValidationError('Invalid phone number')

        return full_phone_number

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
    
################# verifying the otp form #########################


class VerifyOTPForm(forms.Form):
    otp = forms.CharField(max_length=6)


###################Signin form#################################

class SignInForm(forms.Form):
    username= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'UserName'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input--style-2','placeholder': 'Password'}))
    class Meta:
        model = User
        fields = ('username', 'password')


class PasswordResetForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input--style-2', 'placeholder': 'Email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        # Add any additional email validation here if needed
        return email




################## changing the user_details form #####################

class ChangeUserDetails(forms.Form):
    # username = forms.CharField(max_length=100,label='Username:')
    username= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'UserName'}))
    # email = forms.EmailField(label='Email:')
    email= forms.EmailField(widget=forms.EmailInput(attrs={'class': 'input--style-2', 'placeholder': 'Email'}))
    # phone_number = forms.IntegerField(label="Phone Number:")
    phone_number= forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'input--style-2', 'placeholder': 'Phone Number'}))
    # address = forms.CharField(max_length=100,label = 'Address:')
    address= forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Address'}))
    display_picture = forms.FileField(label='Change Display Picture',required=False)


####### This is the class to create an item ########

class ItemForm(forms.ModelForm):
    size = forms.ModelMultipleChoiceField(queryset=None, widget=forms.CheckboxSelectMultiple)
    item_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Item Name'}))
    item_price = forms.FloatField(widget=forms.NumberInput(attrs={'class': 'input--style-2', 'placeholder': 'Item Price'}))
    item_image = forms.FileField(label='Change Display Picture', required=False)
    category = forms.ModelChoiceField(queryset=None, empty_label="Select a category")

    class Meta:
        model = Items
        fields = ['item_name', 'item_price', 'size', 'item_image', 'is_available', 'category']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['size'].queryset = Size.objects.all()
        self.fields['category'].queryset = Category.objects.all()



############ Order form ##############




class OrderForm(forms.ModelForm):
    PAYMENT_CHOICES = (
        ("CASH ON DELIVERY", "COD"),
        ("UPI", "UPI"),
        ("CARD", "CARD"),
    )

    class Meta:
        model = Order
        fields = ['name', 'phone_number', 'zip_code', 'place', 'payment_method']

    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Enter Your Name'}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Enter Your Phone Number'}))
    zip_code = forms.CharField(widget=forms.NumberInput(attrs={'class': 'input--style-2', 'placeholder': 'Enter The Zip Code'}))
    place = forms.CharField(widget=forms.TextInput(attrs={'class': 'input--style-2', 'placeholder': 'Enter The Address'}))
    payment_method = forms.ChoiceField(label='Payment Method', choices=PAYMENT_CHOICES, widget=forms.Select(attrs={'class': 'form-control', 'required': True}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None) # Get the user object from kwargs
        super().__init__(*args, **kwargs)
        if self.user:
            self.fields['address'].initial = self.user.address # Set the default value of the address field to the user's address

templates/edit_item.html
{% extends 'layout.html' %}
{% block content %}
  <h1>Edit {{ item.item_name }}</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
  <a href="{% url 'item_list' %}">Cancel</a>

  {% endblock %}

templates/footer.html
{% extends 'layout.html' %}
{% block content %}
{%load static%}

<!-- ***** Footer Start ***** -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-3">
                <div class="first-item">
                    <div class="logo">
                        <img src="{%static 'images/white-logo.png'%}" alt="hexashop ecommerce templatemo">
                    </div>
                    <ul>
                        <li><a href="#">16501 Collins Ave, Sunny Isles Beach, FL 33160, United States</a></li>
                        <li><a href="#">hexashop@company.com</a></li>
                        <li><a href="#">010-020-0340</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3">
                <h4>Shopping &amp; Categories</h4>
                <ul>
                    <li><a href="#">Men’s Shopping</a></li>
                    <li><a href="#">Women’s Shopping</a></li>
                    <li><a href="#">Kid's Shopping</a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <h4>Useful Links</h4>
                <ul>
                    <li><a href="#">Homepage</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Help</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div class="col-lg-3">
                <h4>Help &amp; Information</h4>
                <ul>
                    <li><a href="#">Help</a></li>
                    <li><a href="#">FAQ's</a></li>
                    <li><a href="#">Shipping</a></li>
                    <li><a href="#">Tracking ID</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="under-footer">
                    <p>Copyright © 2022 HexaShop Co., Ltd. All Rights Reserved. 
                    
                    <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
                    <ul>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
  </footer>

  <!-- footerends  -->



{%endblock%}

templates/forgot_password_confirmation.html
<p>An email has been sent to your registered email address with instructions on how to reset your password.</p>

templates/item_detail.html
<!-- item_detail.html -->

{% extends 'layout.html' %}
{% block content %}

{% load static %}
 <!-- ***** Main Banner Area Start ***** -->
 <div class="page-heading" id="top">
  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <div class="inner-content">
                  <h2>Single Product Page</h2>
                  
              </div>
          </div>
      </div>
  </div>
</div>
<!-- ***** Main Banner Area End ***** -->


 <!-- ***** Product Area Starts ***** -->
 <section class="section" id="product">
  <div class="container">
      <div class="row">
          <div class="col-lg-8">
          <div class="left-images">
              <img src="{{ item.item_image.url }}" style="height: 43vh;" alt="">
              
          </div>
      </div>
      <div class="col-lg-4">
          <div class="right-content">
              <h4>{{ item.item_name }}</h4>
              <span class="price">${{ item.item_price }}</span>
              <ul class="stars">
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
                  <li><i class="fa fa-star"></i></li>
              </ul>
              <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod kon tempor incididunt ut labore.</span>
              <div class="quote">
                  <i class="fa fa-quote-left"></i><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiuski smod.</p>
              </div>
              <form method="post" action="{% url 'add_to_cart' item.pk %}">
                {% csrf_token %}
              <div class="quantity-content">
                <label for="selected_size">Select Size:</label>
                <select name="selected_size" id="selected_size">
                  {% for size in item.size.all %}
                    <option value="{{ size.sizes }}">{{ size.sizes }}</option>
                  {% endfor %}
                </select>
              
                
                
              <div class="total">
                  <h4>Total: ${{item.item_price}}</h4>
                  <div class="main-border-button"><button type="submit" class="btn btn-dark" >Add To Cart</button></div>
                  
              </div>
            </form>
          </div>
      </div>
      </div>
  </div>
</section>

<!-- ***** Product Area Ends ***** -->

{% include 'footer.html' %}

  <!-- <h1>{{ item.item_name }}</h1>
  <h1>{{request.user.username }}</h1>
  <p>Price: ${{ item.item_price }}</p>
  <form method="post" action="{% url 'add_to_cart' item.pk %}">
    {% csrf_token %}
    <label for="selected_size">Select Size:</label>
    <select name="selected_size" id="selected_size">
      {% for size in item.size.all %}
        <option value="{{ size.sizes }}">{{ size.sizes }}</option>
      {% endfor %}
    </select>
  <button type="submit" class="btn btn-dark">Add To Cart</button>

  </form>
  <img src="{{ item.item_image.url }}" alt="{{ item.item_name }} Image" width="200">
  <p>Available: {% if item.is_available %}Yes{% else %}No{% endif %}</p> -->
  
{% endblock %}

templates/order_list.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}

<style>
  /* Custom hover color for the table */
  .table-hover tbody tr:hover {
    background-color: #69656e; /* Change this to your desired hover color */
    color:white;
  }

  /* Styling for the tracking dropdown */
  .form-select {
    width: 150px;
  }

  /* Styling for the "Update" button */
  .btn-primary {
    margin-left: 10px;
  }

  /* Styling for the tracking status badge */
  .badge {
    font-size: 14px;
    padding: 5px 10px;
  }

  /* You can customize the badge colors to match your design */
  .bg-primary {
    background-color: #007bff;
    color: white;
  }

  /* Custom card style */
  .order-card {
    margin-top: 10%;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border: 2px solid #f2f2f2;
    border-radius: 8px;
    padding: 15px;
    margin-bottom: 20px;
  }

  .order-card .card-header {
    background-color: black;
    color: white;
    font-weight: bold;
    padding: 10px;
    border-radius: 8px 8px 0 0;
  }

  .order-card .card-body {
    padding: 10px;
  }

  /* Custom separator style */
  .order-separator {
    border-bottom: 2px solid #f2f2f2;
    margin-bottom: 20px;
  }
</style>

{% if orders %}
<div class="container">
  {% for order in orders %}
  <div class="order-card">
    <div class="card-header">
      Order ID: {{ order.pk }} | UserName: {{ order.user.username }}
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-6">
          <p>Name: {{ order.name }}</p>
          <p>Phone Number: {{ order.phone_number }}</p>
          <p>Zip Code: {{ order.zip_code }}</p>
          <p>Place: {{ order.place }}</p>
          <p>Payment Method: {{ order.get_payment_method_display }}</p>
          {% if request.user.is_superuser %}
          <form method="post" action="{% url 'update_tracking' order.pk %}">
            {% csrf_token %}
            <div class="input-group text-uppercase m-3">
              <select name="tracking" class="form-select text-uppercase">
                {% for key, value in order.TRACKING %}
                <option value="{{ key }}" {% if order.tracking == key %}selected{% endif %}>{{ value }}</option>
                {% endfor %}
              </select>
              <button type="submit" class="btn btn-dark">Update</button>
            </div>
          </form>
          {% else %}
          <span class="badge rounded-pill p-3 m-3 bg-dark text-uppercase">{{ order.get_tracking_display }}</span>
          {% endif %}
        </div>
        
        <div class="col-md-6">
          <table class="table table-bordered table-striped table-hover">
            <thead>
              <tr>
                <th>Item Name</th>
                <th>Item Size</th>
                <th>Item Quantity</th>
                <th>Price</th>
              </tr>
            </thead>
            <tbody>
              {% for order_item in order.orderitem_set.all %}
              <tr>
                <td>{{ order_item.item.item_name }}</td>
                <td>{{ order_item.size.sizes }}</td>
                <td>{{ order_item.quantity }}</td>
                <td>${{ order_item.total_price }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="order-separator"></div>
  {% endfor %}
</div>
{% else %}
<h1 class="text-center display-2" style="margin-top: 20%;">No Orders Found...😢😢😢</h1>
<div class="text-center">
  <a href="{% url 'item_list' %}"><button class="btn btn-dark m-5">Go To Home</button></a>
</div>
{% endif %}
{% endblock %}

templates/reset_password.html
<!DOCTYPE html>
<html>
<head>
    <title>Reset Password</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center mt-5" style="height: 60vh;">
        <div class="card p-4 shadow-sm w-75">
            <h1 class="mb-4 text-center">Reset Password</h1>
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="uidb64" value="{{ uidb64 }}">
                <input type="hidden" name="token" value="{{ token }}">
                <div class="mb-3">
                    <label for="new_password" class="form-label">New Password:</label>
                    <input type="password" id="new_password" name="new_password" class="form-control" required>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-dark">Reset Password</button>
                </div>
            </form>
            {% if messages %}
                <div class="mt-3 alert alert-info">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>

    <!-- Add Bootstrap JS and Popper.js (required for Bootstrap) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/verify.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Meal Mate</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <style>
    HTML CSS JSResult Skip Results Iframe
.height-100 {
    height: 100vh
}

body {
    margin-top: 16%;
    

}

.card {
    width: 500px;
    border: none;
    height: 400px;
    box-shadow: 0px 5px 20px 0px #d2dae3;
    z-index: 1;
    display: flex;
    justify-content: center;
    align-items: center
}

.card h6 {
    color: red;
    font-size: 28px;
}
div {
    font-size: large;
}
.inputs input {
    width: 70%;
    height: 50px;
}

input[type=number]::-webkit-inner-spin-button,
input[type=number]::-webkit-outer-spin-button {
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    margin: 0
}

.card-2 {
    background-color: #fff;
    padding: 10px;
    width: 350px;
    height: 100px;
    bottom: -50px;
    left: 20px;
    position: absolute;
    border-radius: 5px
}

.card-2 .content {
    margin-top: 50px
}

.card-2 .content a {
    color: red
}

.form-control:focus {
    box-shadow: none;
    border: 2px solid red
}

.validate {
    border-radius: 20px;
    height: 40px;
    background-color: red;
    border: 1px solid red;
    width: 140px
}

  </style>
</head>
<body>

  <div class="container height-100 d-flex justify-content-center align-items-center">
    <div class="position-relative">
        <div class="card p-2 text-center">
            <h6>Please enter the one time password <br> to verify your account</h6>
            <div> <span>A code has been sent to</span> <small>Email</small> </div>
            <form method="post">
            {% csrf_token %}
            <div id="otp" class="inputs d-flex flex-row justify-content-center mt-2">
                <input class="m-2 text-center form-control rounded" type="text" id="id_otp" name="otp" maxlength="6" />
            </div>
            <div class="mt-4"> <button class="btn btn-danger px-4 validate">Validate</button> </div>
            </form>
        </div>
    </div>
  </div>

</body>
</html>